# Generated by Django 3.2.8 on 2024-10-31 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postafacil", "0003_auto_20241031_1742"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="cep",
        ),
    ]
